//! Cross-language check against `conformance/launch-hash.json`.
//!
//! These vectors were generated by the TypeScript implementation. If this test fails, the two
//! implementations disagree about what a user consented to — treat it as a correctness bug in
//! whichever side changed, never as a reason to regenerate the vectors.

use mcp_locator_proto::{canonicalize, launch_hash};
use serde_json::{Map, Value};
use std::path::PathBuf;

fn conformance_dir() -> PathBuf {
    // crates/proto -> crates -> broker -> repo root
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("..")
        .join("..")
        .join("conformance")
}

#[test]
fn matches_the_typescript_vectors() {
    let raw = std::fs::read_to_string(conformance_dir().join("launch-hash.json"))
        .expect("conformance/launch-hash.json must exist");
    let doc: Value = serde_json::from_str(&raw).expect("vectors must be valid JSON");
    let vectors = doc["vectors"]
        .as_array()
        .expect("`vectors` must be an array");

    assert!(!vectors.is_empty(), "vector file must not be empty");

    for vector in vectors {
        let description = vector["description"].as_str().unwrap_or("<unnamed>");
        let card = &vector["card"];

        let local = card.get("local");
        let mut subject = Map::new();
        for key in ["launch", "endpoint"] {
            subject.insert(
                key.to_string(),
                local
                    .and_then(|l| l.get(key))
                    .cloned()
                    .unwrap_or(Value::Null),
            );
        }

        assert_eq!(
            canonicalize(&Value::Object(subject)),
            vector["canonical"].as_str().unwrap(),
            "canonical form differs from TypeScript for: {description}"
        );
        assert_eq!(
            launch_hash(card),
            vector["launchHash"].as_str().unwrap(),
            "launch hash differs from TypeScript for: {description}"
        );
    }
}
